### ISSUE TITLE
When using the recommended CommandAppBuilder, how do you specify service lifetimes?

### ISSUE THREAD

**Issue by jamesshenry** [d20Tek/Spectre.Console.Extensions#11]
Can I register a service as Transient or Scoped using the `ITypeRegistrar`?

**Comment by DarthPedro** [comment]
@henry-js  The ITypeRegistrar itself doesn't specify a lifetime for the type. And that is an interface defined in the Spectre.Console package. So all of the implementations in this library are singletons. 

It could be possible to provide configuration to the ITypeRegistrar implementations to say whether the types are scoped, transient, or singletons. But that would apply to all of the types registered, which isn't necessarily what you're looking for either. Another approach could be to implement extension methods on the ITypeRegistrar interface with methods for RegisterScoped and RegisterTransient, so that console apps could pick the lifetime they want for specific types.

What are your requirements/scenarios that you would like to see supported for your app? With those, I can see which options would be best to implement in this library.

**Comment by DarthPedro** [comment]
@henry-js Thanks opening the issue and an initial attempt at implementing it. I took your change and expanded it to all of the other With*Container extension methods, so that it would be supported for all of DI containers this project supports. And, I also made the container parameter optional, so existing code continues to work as-is, and developers can specified the container if they wish.

**Comment by DarthPedro** [comment]
Also, you can use this new functionality in version 1.0.6, which I just published to NuGet.org today.
